import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import { headers } from "next/headers";
import { isRTL } from "react-aria-components/I18nProvider";
import { ClientProviders } from "./provider";
import "./globals.css";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const acceptLanguage = (await headers()).get("accept-language");
  const lang = acceptLanguage?.split(/[,;]/)[0] || "en-US";

  return (
    <html
      lang={lang}
      dir={isRTL(lang) ? "rtl" : "ltr"}
      className={`${archivo.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <ClientProviders lang={lang}>{children}</ClientProviders>
      </body>
    </html>
  );
}